//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehiclesDBEntities : DbContext
    {
        public VehiclesDBEntities()
            : base("name=VehiclesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<feature> features { get; set; }
        public virtual DbSet<vehicleFeature> vehicleFeatures { get; set; }
        public virtual DbSet<vehicleMake> vehicleMakes { get; set; }
        public virtual DbSet<vehicleModel> vehicleModels { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
