//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiclesProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleFeature
    {
        public int vehicleFeaturesId { get; set; }
        public Nullable<int> featureId { get; set; }
        public Nullable<int> vehicleId { get; set; }
    
        public virtual feature feature { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
